### ISSUE TITLE
Crash on creating fluid stack

### ISSUE THREAD

**Issue by cocopuffs99** [jaredlll08/JSON-ables#15]
java.lang.IllegalArgumentException: Empty string not allowed
at net.minecraft.nbt.NBTTagString.(NBTTagString.java:23)
at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:105)
at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:104)
at jsonAbles.api.RecipeRegistry.registerFluids(RecipeRegistry.java:230)
at jsonAbles.JsonAbles.init(JsonAbles.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:530)
at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:215)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:193)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:699)
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:304)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

full log: http://pastebin.com/ceM0EvKu

**Comment by jaredlll08** [comment]
dude, you even replied to the same fucking issue, MAKING MORE ISSUES DOESN'T HELP ALSO POSTING A CRASH WITHOUT THE JSONS DOESN'T HELP, AND THIS IS BASICALLY A FUCKING COPY PASTE OF THE OTHER ISSUE, HECK THIS IS THE EXACT SAME FUCKING ISSUE!

**Comment by cocopuffs99** [comment]
I didnt reply to the same issue, if you look you'll see that other people have this issue also.  Isn't the point of this to post bugs and issues?

**Comment by jaredlll08** [comment]
The point is to reply to the other issue(even closed) to make me more aware
if this
Also, the original issue said it was MF3, I spoke to jaded, it is users
updating jsonables and expecting it to work...

**Comment by cocopuffs99** [comment]
Ok thanks, I will downgrade jsonables, and list future replies to the other issue.
